# Generated by Django 2.2.7 on 2019-11-29 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191128_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
