# Generated by Django 2.2.8 on 2020-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191223_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(blank=True, to='core.Game'),
        ),
    ]
