# Generated by Django 2.2.7 on 2019-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(to='core.Developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='core.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='core.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(to='core.Publisher'),
        ),
    ]
