# Generated by Django 2.2.7 on 2019-11-28 12:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191126_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='websites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
