# Generated by Django 2.2.8 on 2019-12-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
