# Generated by Django 2.2.8 on 2019-12-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_igdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(max_length=3000),
        ),
    ]
