# Generated by Django 2.2.8 on 2019-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191213_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(max_length=5000),
        ),
    ]
