# Generated by Django 2.2.9 on 2020-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
