# Generated by Django 2.2.20 on 2021-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
    ]
