# Generated by Django 2.2.24 on 2021-12-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_confirmemailtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmEmailToken',
        ),
    ]
